os: linux
dist: bionic
language: java

stages:
  - name: build
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: build
      script:
        - ./gradlew build
    - stage: release
      script:
        - ./gradlew provider:shadowJar provider:distZip
        - ./gradlew publish -Dgpr.user=${GPR_USER} -Dgpr.token=${GPR_TOKEN} -Drelease=true

before_deploy:
  - export LIB_JAR_FILE=$(ls build/provider/libs/*all.jar)
  - export DIST_ZIP_FILE=$(ls build/example/distributions/*.zip)

deploy:
  provider: releases
  token: ${ACCESS_TOKEN}
  file:
    - ${LIB_JAR_FILE}
    - ${DIST_ZIP_FILE}
  cleanup: false
  overwrite: true
  on:
    repo: hhu-bsinfo/hadroNIO
    branch: master
    tags: true