os: linux
dist: bionic
language: java

stages:
  - name: build
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: build
      script:
        - ./gradlew build
    - stage: release
      script:
        - ./gradlew clean
        - ./gradlew publish -Dgpr.user=${GPR_USER} -Dgpr.token=${GPR_TOKEN} -Drelease=true
        - export PUBLISH=true

deploy:
  provider: releases
  token: ${ACCESS_TOKEN}
  overwrite: true
  on:
    repo: hhu-bsinfo/hadroNIO
    branch: master
    tags: true
    condition: ${PUBLISH} = true
