os: linux
dist: focal
language: java

stages:
  - name: build
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: build
      before_install:
        - wget -O jdk.tar.gz ${JDK_URL}
        - tar -xzvf jdk.tar.gz -C /tmp
        - echo "org.gradle.java.installations.paths=/tmp/jdk-${JDK_VERSION}" > gradle.properties
      script:
        - ./gradlew build -Dinfinileap=true
    - stage: release
      install:
        - ./gradlew provider:assemble -Dinfinileap=true
      script:
        - ./gradlew clean
        - ./gradlew publish -Dgpr.user=${GPR_USER} -Dgpr.token=${GPR_TOKEN} -Dinfinileap=true -Drelease=true
        - export PUBLISH=true

deploy:
  provider: releases
  token: ${ACCESS_TOKEN}
  overwrite: true
  on:
    repo: hhu-bsinfo/hadroNIO
    branch: master
    tags: true
    condition: ${PUBLISH} = true
