name: release
on:
  push:
    branches:
    tags: 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install OpenJDK 20
        run: wget https://download.java.net/java/GA/jdk20.0.1/b4887098932d415489976708ad6d1a4b/9/GPL/openjdk-20.0.1_linux-x64_bin.tar.gz && tar -xzf openjdk-20.0.1_linux-x64_bin.tar.gz && mv jdk-20.0.1 /usr/lib/jvm

      - name: Publish to Github Package Repository
        run: ./gradlew publish -Dinfinileap=true -Drelease=true -Dgpr.user=${PUBLISH_USER} -Dgpr.token=${PUBLISH_TOKEN}

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/provider/libs/hadronio-*.jar
          env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}